[package]
name = "aca_zk"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.21", default-features = false, features = ['std'] }
ethers-core = { version = "2.0", default-features = false }
serde = { version = "1.0", features = ["derive"] }
